### ISSUE TITLE
ProductIterator Problem

### ISSUE THREAD

**Issue by pascalknecht** [mindkomm/timber-integration-woocommerce#6] opened 2018-09-03 09:09 UTC
Since the ProductIterator only runs on WooCommerce Pages (see https://github.com/mindkomm/timber-integration-woocommerce/blob/master/lib/Timber/Integrations/WooCommerce/WooCommerce.php#L91) I propose to add a custom product setup function to call before rendering products.
Something like that:
`final public function addProductFunction($twig)
	{
		$twig->addFunction(new \Twig_Function('wci_wc_setup_product_data', function($post_id) {
			wc_setup_product_data($post_id);
			return '';
		}));
		return $twig;
	}
`

**Comment by gchtr** [comment] 2018-09-03 11:25
Hey @pascalknecht 

I guess currently there’s no easy way to set a custom iterator when setting up a new `Timber\PostQuery()`.

But maybe instead of adding a new Twig function we could add a `setup_product_data()` method for the [`Product`](https://github.com/mindkomm/timber-integration-woocommerce/blob/master/lib/Timber/Integrations/WooCommerce/Product.php) class?

```php
public function setup_product_data() {
    wc_setup_product_data( $this->ID );
}
```

We could then use this when using products outside of WooCommerce pages:

```twig
{% for product in products %}
    {% do product.setup_product_data() %}
    {% include 'product-teaser.twig' %}	
{% endfor %}
```

What do you think? Would that work, too?

**Comment by pascalknecht** [comment] 2018-09-03 12:50
Ah yeah sure this solution is better than my proposed one.
I only see two possibilities for this to go further:
- Create pull request in Timber to allow `Timber::get_posts` to have an optional parameter PostIterator. 
- Create the function like you suggested

Guess the second one will probably be easier. Maybe we should think about dropping the iterator all together to not have confusion when the iterator works (currently on WooCommerce Pages) and not. What do you think about that?

**Comment by gchtr** [comment] 2018-09-03 13:28
Thanks a lot for giving your input and for thinking about the architecture here. I’m very glad to get feedback from other developers.

I think an optional parameter for `PostQuery()` (`get_posts()` will be deprecated in Timber 2.0) would make sense either way. I’ll take this on my todo list.

I agree that there might be confusion about when the iterator works and when not. I guess I didn’t think too much about the use case of products on other pages. Like you suggest, it’s probably better if this is more consistent. So I’d be fine with removing the hook that adds the iterator automatically.

But instead of dropping it completely, we could use it to create a wrapper function for Twig. It’s already possible to convert an array of post IDs or posts to `Timber\Post` objects in Twig (though that is currently not very well documented):

```twig
{% for post in Post(array_of_post_ids) %}
    {% include 'post-teaser.twig' %}	
{% endfor %}
```

Maybe we could use the same pattern for `Product` objects:

```twig
{% for product in Product(products) %}
    {% include 'product-teaser.twig' %}	
{% endfor %}
```

I’m not quite happy with using `Post()` or `Product()`, because it’s a singular name and I wouldn’t except it to take an array as an argument. So maybe we could use `ProductIterator()`:

```twig
{% for product in ProductIterator(products) %}
    {% include 'product-teaser.twig' %}	
{% endfor %}
```

I’ll have to check out how this would work and if we could swap out the post iterator like this.

But then, we’d also have to consider the use case when we don’t have a collection of products, but only one product:

```twig
{% include 'product-teaser.twig' with { product: Product(myproduct) } %}	
```

We could setup the post data in Twig’s `Product()` function. But we wouldn’t do it in the constructor for the `Product` object, because the constructor shouldn’t change globals to prevent unexpected behavior. That’s what the `$product->setup_product_data()` function would be for.

What do you think? 😊

**Comment by pascalknecht** [comment] 2018-09-03 14:06
I don't really like to use the Post function in Timber. It always feels a little bit hacky to do functionality in Twig. I just got another idea though: Encapsulate the product variable in the product class. Set the product property of product to private. Then create a getter for it and whenever that getter is called setup the product data because only then the product data is accessed. But I think this will only work if a product variable is accessed before the first `{% do action('woocommerce_') %}`. Any idea which could fix this? Otherwise I would prefer the setup function which you were talking about earlier.

**Comment by gchtr** [comment] 2018-09-05 13:00
Hey @pascalknecht 

Yeah, using these functions in Twig always seems a little hacky. But sometimes it’s the quickest solution. Maybe not in a WooCommerce setup, though.

I thought about the setup function a little bit more and came up with a pull request on Timber that could solve the problem here as well: https://github.com/timber/timber/pull/1778. We could add a `setup()` method for `Product`:

```php
class Product extends Timber\Post {
    public function setup( $loop_index = 0 ) {
        parent::setup( $loop_index );

        wc_setup_product_data( $this->ID );

        return $this;
    }
}		
```

And it should be possible to remove the PostsIterator as well. I guess then it could work «out of the box», without having to call any additional function.

**Comment by pascalknecht** [comment] 2018-09-05 20:20
@gchtr  Sound like a great solution 👍

**Comment by gchtr** [comment] 2023-01-13 16:55
Closing this. This will be solved when Timber 2 is released.

**Closed as completed by gchtr** 2023-01-13 16:55 UTC
