### ISSUE TITLE
Posts in archive-product.twig instead of Products

### ISSUE THREAD

**Issue by tameroski** [mindkomm/timber-integration-woocommerce#16] opened 2020-10-09 16:28 UTC
Hi,

That's a nice piece of code we have here, thanks for sharing your work !

Everything's fine with the default `single-product.twig` & `content-product.twig` files i copied from the package, but i have an issue with `archive-product.twig` where the `wc_get_loop_prop loop` is returning `Timber\Integrations\WooCommerce\Product` instances of blog posts instead of products, here :

```twig
<ul class="products columns-{{ fn('wc_get_loop_prop', 'columns')|e }}">
      {% if fn('wc_get_loop_prop', 'total') %}
          {% for product in posts if fn('have_posts') %}
             {{ dump(product) }} {# <- Got Blog posts as Timber\Integrations\WooCommerce\Product here #}

            {{ fn('wc_get_template_part', 'content', 'product' ) }}
        {% endfor %}
    {% endif %}
</ul>
```

I could force the posts in the context in `woocommerce.php`, but that might not be the best solution :

```php
add_filter('timber/woocommerce/context', function($context){
    if ( is_archive() ) {
            $posts = Timber::get_posts();
            $context['posts'] = $posts;
        }
    return $context;
});

Timber\Integrations\WooCommerce\WooCommerce::render_default_template();
```

Any hint on what could be the problem ?

**Comment by gchtr** [comment] 2020-10-10 10:26
Hey @tameroski! Thanks for the kind words :).

Yeah, this was actually a compatibility problem when using posts that don’t have the `product` post type on a shop page. I naively checked for `is_woocommerce()` and applied the `Product` class to all Timber posts in that condition. I’ve been working on a solution for this in the last couple of weeks, because I ran into the same problems and I think I now have a solution that works well. Check out the Release Candidate: https://github.com/mindkomm/timber-integration-woocommerce/releases/tag/0.6.0-rc.1.

I’d be happy if you could test it and report back if it solves your problem:

```bash
composer require mindkomm/timber-integration-woocommerce:dev-master
```

**Comment by tameroski** [comment] 2020-10-12 16:05
Hi @gchtr !

Thanks for the update.
Unfortunately, after upgrading to dev:master and updating the twig templates in my theme, i still got the same behaviour

```twig
{% if fn('wc_get_loop_prop', 'total') %}
    {% for product in posts %}

        {{ dump(product) }} {#  <-- Still got a list of blog posts here, instead of a list of products #}

        {##
         # Depending on your WooCommerce display settings, the
         # `woocommerce_product_subcategories` function might reset the $wp_query global. By
         # calling `have_posts()`, we check if there are posts we can display.
         #}
        {% if fn('have_posts') %}
            {{ fn('wc_get_template_part', 'content', 'product' ) }}
        {% endif %}
    {% endfor %}
{% endif %}
```

The products count displayed through `{% do wc_action('woocommerce_archive_description') %}` just before the loop is accurate, though (it already was before the update). This is weird.

**Comment by gchtr** [comment] 2020-10-12 16:18
@tameroski Okay, in that case we’ll need to investigate further. Just so I understand you correctly:

- Do you want to display any blog posts *alongside* your products on your products archive, or do you only want your products on your products archive?
- What page did you set as your page for posts in **Settings** → **Reading**?
- Is your products archive also your front page, or a different page?

**Comment by tameroski** [comment] 2020-10-12 16:32
- No, i don't need to display any blog posts alongside my products in that project
- The posts page is a custom "Blog" page. So is the front page.
- The archive page is not the front page

**Comment by gchtr** [comment] 2020-10-12 17:58
Damn, I can’t reproduce your issue. So let’s see:

**woocommerce.php**

```php
// Do you have posts or products here?
var_dump( Timber::get_posts() );

Timber\Integrations\WooCommerce\WooCommerce::render_default_template();
```

**archive-product.twig**

```twig 
{{ dump(posts) }} {#  Do you have posts or products here? #}

{% if fn('wc_get_loop_prop', 'total') %}
	{{ dump(posts) }} {#  Do you have posts or products here? #}

    {% for product in posts %}
        {% if fn('have_posts') %}
			{{ dump(product) }} {#  Do you have a blog post or a product here? #}

            {{ fn('wc_get_template_part', 'content', 'product' ) }}
        {% endif %}
    {% endfor %}
{% endif %}
```

- What do you get in your **views/woocommerce/content-product.twig** file? Blog posts or products?
- What else have you got in your **archive-product.twig** view? Is your code example everything you have in there?
- Could it be that something else is hooking into the `timber/context` filter an is updating `posts`? Another plugin? Something else in your theme?
- Does flushing your permalinks help?
- Sometimes we still see weird compatibility bugs with other plugins. So does deactivating other plugins (except for WooCommerce) help?

**Comment by tameroski** [comment] 2020-10-13 07:58
Hi,

So i made a few tests as requested. Here's what i get :

**woocommerce.php**

`Timber::get_posts()` returns an array of `Timber\Integrations\WooCommerce\Product`. So far so good.

**archive-product.twig**

```twig
{{ dump(posts) }} {#  I've got a Timber\PostQuery with "post_type=post" here #}

{% if fn('wc_get_loop_prop', 'total') %}
	{{ dump(posts) }} {#  Same here. I've got a Timber\PostQuery with "post_type=post" here #}

    {% for product in posts %}
        {% if fn('have_posts') %}
			{{ dump(product) }} {#  Got a Timber\Post #}

            {{ fn('wc_get_template_part', 'content', 'product' ) }}
        {% endif %}
    {% endfor %}
{% endif %}
```

**content-product.twig**

Here is the weird part : i've got a `WC_Product_Simple` here, but the same on each iteration.
And the hooks are returning the Timber\Post data :sweat_smile:

**Other questions**
- My templates are just simple copies of the ones in the packages. I only changed `{% for posts in posts %}` for `{% for product in posts %}` so i can get a product var in content-product. If i rollback this change, i've got `Timber\Integrations\WooCommerce\Product` instances in `content-product.twig` instead of `WC_Product_Simple` :confused:
- Disabling all other plugins had no effect.
- Flushing the permalinks had no effect.
- The only thing hooking on `timber/context` is the package's Woocommerce.php

I'll try to have a deeper look into this on my side today.

**Comment by tameroski** [comment] 2020-10-13 08:49
Ok, i finally found what's the issue. Spoiler : i'm very sorry for wasting some of your time.

As i display blog posts on several pages in the theme, i was adding them to the context of all pages, including archives, but did'nt pay attention to that ... Sorry for the earlier misleading comment.

So the workaround for displaying posts and products on the same page, is adding posts to the context with a different variable name, i guess ?

**Comment by gchtr** [comment] 2020-10-13 09:03
@tameroski Cool, I’m glad you found the issue and that it’s not directly related to the integration. And no worries, we’ve all been there. 😊

> So the workaround for displaying posts and products on the same page, is adding posts to the context with a different variable name, i guess ?

Well, if you want to keep your global `posts` variable, you could update your WooCommerce pages to use `products` instead of `posts`. In the newest version of the integration, you can pass a context to `render_default_template()` that is merged with `Timber::get_context()`.

**woocommerce.php**

```php
Timber\Integrations\WooCommerce\WooCommerce::render_default_template( [
    'products' => Timber::get_posts(),
] );
```

Then, in your Twig file, you would have to make sure that you loop over `products` instead of `posts`.

```twig
{% for product in products %}
    {% if fn('have_posts') %}
        {{ fn('wc_get_template_part', 'content', 'product' ) }}
    {% endif %}
{% endfor %}
```

However, because in Timber using `posts` as the name for default query, you might run into other issues. So I would actually recommend to use a different variable name for your blog posts in your global context.

And I would add conditial checks for when your blog posts are actually added to the global context. Maybe you could also write a small function that would get the blog posts when needed:

```twig
{% for post in fn('theme_get_blog_posts') %}

{% endfor %}
```

**functions.php**

```php
function theme_get_blog_posts() {
	return Timber::get_posts( [
        // Your custom blog post query here.
    ] );
}
```

**Comment by gchtr** [comment] 2020-11-25 20:06
I think I can close this :)

**Closed as completed by gchtr** 2020-11-25 20:06 UTC
